[workspace]
channels = ["conda-forge"]
name = "skill-forge"
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]

[tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"
build-new = "rattler-build build -c https://prefix.dev/skill-forge -c conda-forge --recipe-dir recipes/ --skip-existing=all"
build-all = "rattler-build build -c https://prefix.dev/skill-forge -c conda-forge --recipe-dir recipes/"

[dependencies]
skills-ref = "*"
go-yq = "*"
rattler-build = "*"
pre-commit = "*"
check-jsonschema = "*"
shellcheck = "*"
pre-commit-hooks = "*"
taplo = "*"
typos = "*"
zizmor = "*"

[feature.generate-gws-cli.dependencies]
python = ">=3.12"
"ruamel.yaml" = ">=0.18"

[feature.generate-gws-cli.tasks]
generate-gws-cli = "python recipes/gws-cli/generate.py"

[environments]
default = []
generate-gws-cli = { features = [
  "generate-gws-cli",
], no-default-feature = true }
