"""Generate recipe.yaml for gws-cli skills from upstream SKILL.md frontmatter."""

import sys
from pathlib import Path
from urllib.request import urlopen

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

REPO = "googleworkspace/cli"
REPO_URL = f"https://github.com/{REPO}"
RAW_URL = f"https://raw.githubusercontent.com/{REPO}/main"
REV = "1308786bdb0cb88e400bc4311b1dd224c7aa2aee"


def fetch(url):
    with urlopen(url) as resp:
        return resp.read().decode()


def get_skills():
    """Get skill names from the skills.md documentation page."""
    content = fetch(f"{RAW_URL}/docs/skills.md")
    skills = []
    for line in content.splitlines():
        # Links like [gws-calendar](../skills/gws-calendar/SKILL.md)
        if "](../skills/" in line:
            path = line.split("](../skills/")[1].split("/")[0]
            if path not in skills:
                skills.append(path)
    return sorted(skills)


def parse_skill_md(skill_name):
    """Extract description and required skills from SKILL.md YAML frontmatter."""
    content = fetch(f"{RAW_URL}/skills/{skill_name}/SKILL.md")
    # Parse YAML frontmatter between --- markers
    parts = content.split("---", 2)
    yml = YAML()
    frontmatter = yml.load(parts[1])
    description = frontmatter.get("description", skill_name)
    required_skills = (
        frontmatter.get("metadata", {}).get("openclaw", {}).get("requires", {}).get("skills", [])
    )
    return description, required_skills


def package_name(skill):
    """Convert a skill directory name to a conda package name."""
    if skill.startswith("gws-"):
        return f"agent-skill-{skill}"
    return f"agent-skill-gws-{skill}"


def build_output(skill, description, required_skills):
    run_deps = [package_name(s) for s in required_skills]
    if skill != "gws-shared" and package_name("gws-shared") not in run_deps:
        run_deps.insert(0, package_name("gws-shared"))

    requirements = {"run_constraints": ["gws >=0.16.0,<1"]}
    if run_deps:
        requirements["run"] = run_deps

    return {
        "package": {
            "name": package_name(skill),
            "version": "${{ version }}",
        },
        "build": {
            "noarch": "generic",
            "script": [
                f"mkdir -p $PREFIX/share/agent-skills/{skill}",
                f"cp $SRC_DIR/skills/{skill}/SKILL.md $PREFIX/share/agent-skills/{skill}/SKILL.md",
            ],
        },
        "requirements": requirements,
        "tests": [
            {
                "package_contents": {
                    "files": [f"share/agent-skills/{skill}/SKILL.md"],
                    "strict": True,
                },
            },
            {
                "script": [f"agentskills validate $CONDA_PREFIX/share/agent-skills/{skill}"],
                "requirements": {"run": ["skills-ref"]},
            },
        ],
        "about": {
            "summary": DoubleQuotedScalarString(f"Agent skill: {description}"),
            "license": "Apache-2.0",
            "license_file": "LICENSE",
            "homepage": REPO_URL,
            "repository": REPO_URL,
            "documentation": f"{REPO_URL}/blob/main/docs/skills.md",
        },
    }


def _spaced_seq(items):
    """Create a YAML sequence with blank lines between items."""
    seq = CommentedSeq(items)
    for i in range(1, len(items)):
        seq.yaml_set_comment_before_after_key(i, before="\n")
    return seq


def main():
    skills = get_skills()

    recipe = CommentedMap()
    recipe.yaml_set_start_comment("This file is auto-generated by generate.py. Do not edit manually.")
    recipe["context"] = {"version": DoubleQuotedScalarString("0.0.1")}
    recipe["source"] = {"git": REPO_URL, "rev": REV}
    outputs = []
    for skill in skills:
        description, required_skills = parse_skill_md(skill)
        outputs.append(build_output(skill, description, required_skills))
    recipe["outputs"] = _spaced_seq(outputs)
    recipe.yaml_set_comment_before_after_key("source", before="\n")
    recipe.yaml_set_comment_before_after_key("outputs", before="\n")

    yml = YAML()
    yml.default_flow_style = False
    yml.width = 4096
    yml.indent(mapping=2, sequence=4, offset=2)

    out_path = Path(__file__).parent / "recipe.yaml"
    with open(out_path, "w") as f:
        yml.dump(recipe, f)
    print(f"Generated {out_path} with {len(skills)} outputs")


if __name__ == "__main__":
    main()
