context:
  skill: writing-tests

package:
  name: agent-skill-${{ skill }}
  version: "0.0.1"

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/share/agent-skills/${{ skill }}
    - cp $RECIPE_DIR/SKILL.md $PREFIX/share/agent-skills/${{ skill }}/SKILL.md

tests:
  - package_contents:
      files:
        - share/agent-skills/${{ skill }}/SKILL.md
      strict: true
  - script:
      - agentskills validate $CONDA_PREFIX/share/agent-skills/${{ skill }}
    requirements:
      run:
        - skills-ref

about:
  summary: Guidelines for writing tests
  description: |
    TODO: Add description
  homepage: https://github.com/pavelzw/skill-forge
  repository: https://github.com/pavelzw/skill-forge
  license: BSD-3-Clause
  license_file: LICENSE
