context:
  skill: sqlalchemy

package:
  name: agent-skill-${{ skill }}
  version: "0.0.2"

source:
  url: https://raw.githubusercontent.com/sqlalchemy/sqlalchemy/refs/heads/main/LICENSE
  sha256: e862bb5b904fb5513c3e14288d7a25a12eb0ecc7847a0a965d310e9a955e7cb9

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/share/agent-skills/${{ skill }}
    - cp $RECIPE_DIR/SKILL.md $PREFIX/share/agent-skills/${{ skill }}/SKILL.md

requirements:
  run_constraints:
    - sqlalchemy >=2.0.46,<3

tests:
  - package_contents:
      files:
        - share/agent-skills/${{ skill }}/SKILL.md
      strict: true
  - script:
      - agentskills validate $CONDA_PREFIX/share/agent-skills/${{ skill }}
    requirements:
      run:
        - skills-ref

about:
  summary: Agent skill for SQLAlchemy ORM and SQL toolkit
  description: |
    Python SQL toolkit and Object Relational Mapper (ORM):
    - Define models and build queries
    - Manage sessions and transactions
    - Interact with SQL databases using Python objects
  homepage: https://www.sqlalchemy.org
  repository: https://github.com/sqlalchemy/sqlalchemy
  documentation: https://docs.sqlalchemy.org
  license: MIT
  license_file: LICENSE
