context:
  skill: polars
package:
  name: agent-skill-${{ skill }}
  version: "0.0.3"
source:
  git: https://github.com/k-dense-ai/claude-scientific-skills
  rev: 3a5f2e2227d64679bbe998acfea53007102b4d94
  patches:
    - fix-skill.patch
build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/share/agent-skills/${{ skill }}
    - cp -R scientific-skills/${{ skill }}/* $PREFIX/share/agent-skills/${{ skill }}
requirements:
  run_constraints:
    - polars >=1.38.0,<2
tests:
  - package_contents:
      files:
        - share/agent-skills/${{ skill }}/SKILL.md
  - script:
      - agentskills validate $CONDA_PREFIX/share/agent-skills/${{ skill }}
    requirements:
      run:
        - skills-ref
about:
  summary: Agent skill for Polars DataFrame library
  description: |
    Fast in-memory DataFrame library for datasets that fit in RAM:
    - Lazy evaluation and parallel execution
    - Apache Arrow backend for efficient data processing
    - ETL pipelines and data analysis
  homepage: https://skills.sh/k-dense-ai/claude-scientific-skills/polars
  repository: https://github.com/k-dense-ai/claude-scientific-skills
  documentation: https://skills.sh/k-dense-ai/claude-scientific-skills/polars
  license: MIT
  license_file: LICENSE.md
