context:
  skill: typst

package:
  name: agent-skill-${{ skill }}
  version: "0.0.1"

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/share/agent-skills/${{ skill }}
    - cp $RECIPE_DIR/SKILL.md $PREFIX/share/agent-skills/${{ skill }}/SKILL.md
    - cp -R $RECIPE_DIR/references $PREFIX/share/agent-skills/${{ skill }}/

tests:
  - package_contents:
      files:
        - share/agent-skills/${{ skill }}/SKILL.md
        - share/agent-skills/${{ skill }}/references/*.md
      strict: true
  - script:
      - agentskills validate $CONDA_PREFIX/share/agent-skills/${{ skill }}
    requirements:
      run:
        - skills-ref

about:
  summary: ${{ skill }} agent skill
  homepage: https://typst.app
  repository: https://github.com/typst/typst
  documentation: https://typst.app/docs
  license: Apache-2.0
