context:
  skill: typst

package:
  name: agent-skill-${{ skill }}
  version: "0.0.3"

source:
  url: https://raw.githubusercontent.com/typst/typst/refs/heads/main/LICENSE
  sha256: 62c7a1e35f56406896d7aa7ca52d0cc0d272ac022b5d2796e7d6905db8a3636a

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/share/agent-skills/${{ skill }}
    - cp $RECIPE_DIR/SKILL.md $PREFIX/share/agent-skills/${{ skill }}/SKILL.md
    - cp -R $RECIPE_DIR/references $PREFIX/share/agent-skills/${{ skill }}/

requirements:
  run_constraints:
    - typst >=0.14.2,<0.15

tests:
  - package_contents:
      files:
        - share/agent-skills/${{ skill }}/SKILL.md
        - share/agent-skills/${{ skill }}/references/*.md
      strict: true
  - script:
      - agentskills validate $CONDA_PREFIX/share/agent-skills/${{ skill }}
    requirements:
      run:
        - skills-ref

about:
  summary: ${{ skill }} agent skill
  homepage: https://typst.app
  repository: https://github.com/typst/typst
  documentation: https://typst.app/docs
  license: Apache-2.0
  license_file: LICENSE
